blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://docs.actinium.top/Actinium/gettingStarted.html
    about: Read docs before opening a issue!
  - name: Discord
    url: https://discord.gg/VeKXskHksh
    about: Join our Discord server for support or to just chat!
  - name: Report a security vulnerability
    url: https://github.com/actinium-studios/Actinium/security/advisories/new
    about: Please report security issues privately here, not in a public issue.
